services:
  app:
    build: .
    ports:
      - "3009:3009"
    volumes:
      - .:/app:ro  # Mount the current directory as read-only
    working_dir: /root/
    environment:
      ENV: docker
      PORT: 3009
      LOCAL_DB_HOST: db
      LOCAL_DB_PORT: 3306
      LOCAL_DB_USERNAME: root
      LOCAL_DB_PASSWORD: rootpassword
      LOCAL_DB_NAME: xyz_multifinance_db
      REDIS_ADDRESS: redis:6379
      # Add all other required environment variables here
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: xyz_multifinance_db
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - backend

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge