services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=development
      - APP_PORT=8080
      - DEV_DB_HOST=db
      - DEV_DB_PORT=3306
      - DEV_DB_USERNAME=root
      - DEV_DB_PASSWORD=password
      - DEV_DB_NAME=gofiber_db
      - REDIS_HOST=redis
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass redispass
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge